### ISSUE TITLE
example.py

### ISSUE THREAD

**Issue by buletinonline** [TUANB4DUT/TOOLSINSTALLERv4#1]
Traceback (most recent call last):
  File "example.py", line 55, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/data/data/com.termux/files/home/TOOLSINSTALLERv4/instabot.py/src/instabot.py", line 203, in __init__
    self.login()
  File "/data/data/com.termux/files/home/TOOLSINSTALLERv4/instabot.py/src/instabot.py", line 272, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/data/data/com.termux/files/home/TOOLSINSTALLERv4/instabot.py/src/userinfo.py", line 44, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "/data/data/com.termux/files/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/data/data/com.termux/files/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/data/com.termux/files/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by buletinonline** [comment]
gimana cara benerinya bang?
